server:
  port: 8080

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
    healthcheck:
      enabled: true
    eureka-service-url-poll-interval-seconds: 60
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: qconfig
    prefer-ip-address: true
    health-check-url-path: /health
    status-page-url-path: /info
  server:
    peer-eureka-status-refresh-time-interval-ms: 60000
    enable-self-preservation: false