server:
  port: 8083


eureka:
  instance:
    hostname: qconfig.com
    prefer-ip-address: true
    health-check-url-path: /health
    status-page-url-path: /info
    appname: qconfig
  server:
    peer-eureka-nodes-update-interval-ms: 60000
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    eureka-service-url-poll-interval-seconds: 10


spring:
  profiles:
    include:
      - db
  application:
    name: qconfig.server

qconfig:
  server:
    enable: true
    # 数据库eureka service url 刷新时间
    refresh_interval: 60
    auto_register: true

