server:
  port: 8080

eureka:
  instance:
    hostname: QConfig
    prefer-ip-address: true
    health-check-url-path: /health
    status-page-url-path: /info
  server:
    peer-eureka-nodes-update-interval-ms: 60000
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone:
    eureka-service-url-poll-interval-seconds: 60
